//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawnshop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractProduct
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public bool IsRedeemed { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Product Product { get; set; }
    }
}
