//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawnshop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public bool IsSold { get; set; }
        public bool IsRedeemed { get; set; }
        public int ContractId { get; set; }
        public Nullable<System.DateTime> SoldDate { get; set; }
        public Nullable<System.DateTime> RedeemedDate { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
